[project]
name = "pricepilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic-settings>=2.8.1",
    "pytz>=2025.2",
    "sqlalchemy[asyncio]>=2.0.39",
]
